import { Routes } from '@angular/router';
import { Api } from './sections/api/api';
import { Compact } from './sections/compact/compact';
import { DisplayGrid } from './sections/displayGrid/display-grid';
import { Drag } from './sections/drag/drag';
import { DynamicWidgets } from './sections/dynamicWidgets/dynamic-widgets';
import { EmptyCell } from './sections/emptyCell/empty-cell';
import { GridEvents } from './sections/gridEvents/grid-events';
import { GridMargins } from './sections/gridMargins/grid-margins';
import { GridSizes } from './sections/gridSizes/grid-sizes';
import { GridTypes } from './sections/gridTypes/grid-types';
import { Home } from './sections/home/home';
import { Items } from './sections/items/items';
import { Misc } from './sections/misc/misc';
import { MultiLayer } from './sections/multiLayer/multi-layer';
import { Push } from './sections/push/push';
import { Resize } from './sections/resize/resize';
import { Rtl } from './sections/rtl/rtl';
import { Swap } from './sections/swap/swap';
import { TrackBy } from './sections/trackBy/track-by';

export const appRoutes: Routes = [
  { path: '', component: Home },
  { path: 'api', component: Api },
  { path: 'compact', component: Compact },
  { path: 'displayGrid', component: DisplayGrid },
  { path: 'drag', component: Drag },
  { path: 'dynamicWidgets', component: DynamicWidgets },
  { path: 'emptyCell', component: EmptyCell },
  { path: 'gridEvents', component: GridEvents },
  { path: 'gridMargins', component: GridMargins },
  { path: 'gridSizes', component: GridSizes },
  { path: 'gridTypes', component: GridTypes },
  { path: 'items', component: Items },
  { path: 'trackBy', component: TrackBy },
  { path: 'push', component: Push },
  { path: 'resize', component: Resize },
  { path: 'swap', component: Swap },
  { path: 'multiLayer', component: MultiLayer },
  { path: 'misc', component: Misc },
  { path: 'rtl', component: Rtl },
  { path: '**', redirectTo: '' }
];
